# Generated by Django 5.2.6 on 2025-09-24 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('En Revisión', 'En Revisión'), ('En Subsanación', 'En Subsanación'), ('En Planificación', 'En Planificación'), ('En Ejecución', 'En Ejecución'), ('Revisión de Evidencias', 'Revisión de Evidencias'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Borrador', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('esquema_certificacion', models.CharField(blank=True, max_length=100)),
                ('sistema_gestion', models.TextField(blank=True, help_text='Aplicable para certificaciones bajo el esquema 6 de la norma ISO/IEC 17067:2013', null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='expedientes.empresa')),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Producto', 'Producto'), ('Proceso', 'Proceso'), ('Servicio', 'Servicio')], max_length=30)),
                ('descripcion', models.TextField()),
                ('referencia_normativa', models.TextField(blank=True)),
                ('esquema_certificacion', models.CharField(blank=True, max_length=100)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcances', to='expedientes.solicitud')),
            ],
        ),
    ]
