# Generated by Django 5.2.6 on 2025-09-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_solicitud_alcance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_proceso/')),
                ('alcance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_proceso', to='expedientes.alcance')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('identificacion_interna', models.CharField(blank=True, max_length=50)),
                ('hoja_vida', models.FileField(blank=True, null=True, upload_to='equipos/hojas_vida/')),
                ('alcance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_clave', to='expedientes.alcance')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('formacion', models.CharField(blank=True, max_length=100)),
                ('experiencia', models.TextField(blank=True)),
                ('alcance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_clave', to='expedientes.alcance')),
            ],
        ),
    ]
