# Generated by Django 5.2.6 on 2025-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_documentoproceso_equipoclave_personaclave'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcance',
            name='revision_conforme',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alcance',
            name='revision_observaciones',
            field=models.TextField(blank=True),
        ),
    ]
