# Generated by Django 5.2.6 on 2025-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_alcance_revision_conforme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('costo_dia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('campo_accion', models.TextField(blank=True, help_text='Describa las áreas de especialización, separadas por comas.')),
            ],
        ),
    ]
