# Generated by Django 5.2.6 on 2025-09-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_evaluador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Auditoría en sitio, Revisión documental inicial', max_length=255)),
                ('fecha_inicio_planificada', models.DateField()),
                ('dias_planificados', models.PositiveIntegerField(default=1)),
                ('fecha_limite_evidencias', models.DateField()),
                ('estado', models.CharField(default='Planificada', max_length=50)),
                ('evaluador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedientes.evaluador')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='expedientes.solicitud')),
            ],
        ),
    ]
