# Generated by Django 5.2.6 on 2025-09-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_evaluador_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('revision_conforme', models.BooleanField(default=None, null=True)),
                ('revision_observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='expedientes.actividad')),
            ],
        ),
    ]
