# Generated by Django 5.2.6 on 2025-09-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0008_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('Planificada', 'Planificada'), ('En Ejecución', 'En Ejecución'), ('Con Inconsistencias', 'Con Inconsistencias'), ('Completada', 'Completada')], default='Planificada', max_length=50),
        ),
    ]
