# Generated by Django 5.2.6 on 2025-09-25 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0011_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Queja de Tercero', 'Queja de Tercero'), ('Apelación del Cliente', 'Apelación del Cliente'), ('Amonestación', 'Amonestación'), ('Sanción', 'Sanción'), ('Vigilancia', 'Vigilancia')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('En Investigación', 'En Investigación'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='incidencias/')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='expedientes.solicitud')),
            ],
        ),
    ]
